### ISSUE TITLE
Averaging function causes "Sample frequency too fast" to display.

### ISSUE THREAD

**Issue by haydnw** [haydnw/AirPi#11]
Enabling the averaging function can cause the "Sample frequency too fast" warning message to display, even if the sample frequency is not too fast.

Note that the values output by the averaging function are correct; it is only the display of the warning message which is incorrect.

Probably related to [issue #10](https://github.com/haydnw/AirPi/issues/10).

**Comment by wingers999** [comment]
I still get this message even with averaging turned off- my sample frequency is every 20 minutes!!

**Comment by haydnw** [comment]
Hi. Yes, as mentioned above see issue #10. In fact, I'll close this and just focus on that one.
