### ISSUE TITLE
Outputs: faild to import plugin Calibration

### ISSUE THREAD

**Issue by geo81** [haydnw/AirPi#13]
I get this error when I enable the Calibration plugin. Error: faild to import....

**Comment by wingers999** [comment]
same problem here

**Comment by haydnw** [comment]
Please try latest commit (4e03f5e3fc). Not tested extensively, but I will not have much time over the next few days.

**Comment by wingers999** [comment]
update, but won't run at all - get following output

Loading: OUTPUTS
Traceback (most recent call last):
  File "/home/pi/AirPi/airpi.py", line 1354, in <module>
    PLUGINSOUTPUTS = set_up_outputs()
  File "/home/pi/AirPi/airpi.py", line 525, in set_up_outputs
    OUTPUTCONFIG.read(CFGPATHS['outputs'])
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/pi/AirPi/cfg/outputs.cfg, line: 1
'\xef\xbb\xbf# Note that these options are used in airpi.py to determine whether a\n'

**Comment by haydnw** [comment]
OK, I can't reproduce this. I've tried something in commit 98fc5ef42d so testing would be appreciated. Thanks.

**Comment by haydnw** [comment]
Further to comments in 98fc5ef, try 3f42439 which should fix both the [Notes] and Ubidots issues.

**Comment by wingers999** [comment]
updated to latest version but still getting errors:-

Loading: OUTPUTS
Traceback (most recent call last):
  File "/home/pi/AirPi/airpi.py", line 1356, in <module>
    PLUGINSOUTPUTS = set_up_outputs()
  File "/home/pi/AirPi/airpi.py", line 525, in set_up_outputs
    OUTPUTCONFIG.read(CFGPATHS['outputs'])
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/pi/AirPi/cfg/outputs.cfg, line: 1
'\xef\xbb\xbf[Notes]\r\n'

Any ideas?

**Comment by wingers999** [comment]
FIXED - because I had edited outputs.cfg file in windows (as was easier for me to enter all udibots IDs etc) it had changed format from UNIX to DOS so EOL format was wrong - changed it back in NotePad++ and now working fine

**Comment by haydnw** [comment]
OK, try again with bbb1e9a. If that doesn't work, try deleting the entire [Notes] section and then let me know how you get on.

**Comment by haydnw** [comment]
Ah great. I was wondering about the bits before [Notes] but it was working for me. Thanks for letting me know.

**Comment by wingers999** [comment]
think we both commented at same time - is now working, see my last comment - was down to format of the cfg file

I assume calibration still an issue though? as doesn't work if I have calibration turned on for print or ubidots output

Also, unrelated but any idea how I can fix issue with light sensor causing errors at night (i.e. Error: Check wiring for the LDR measurement - full voltage detected on ADC input 0)

**Comment by haydnw** [comment]
Calibration should be working in 213d0b7

Will have a look at LDR now.

**Comment by wingers999** [comment]
thanks :)
