### ISSUE TITLE
error with ubidots plugin

### ISSUE THREAD

**Issue by wingers999** [haydnw/AirPi#14]
get following error with it enabled:-

Missing config section for plugin Ubidot.
ERROR:   Failed to import plugin Ubidots

**Comment by haydnw** [comment]
Fixed in commit 6ac75dba5e. Thanks for reporting.

**Comment by wingers999** [comment]
thanks - just updated, but now not running at all - just does normal countdown to start and then says INFO:    Starting sampling... - and doesn't do anything else, no results on screen or nothing??!? just got print and ubidots enabled

**Comment by haydnw** [comment]
I've just made a minor tweak and committed as 07e4f95dd8, so please give that a go and see what happens. All working perfectly here, so difficult to test. If it doesn't work then:

1) Please post the [Ubidots] section of your `cfg/outputs.cfg` file. Remove or obscure the `token` line, but leave everything involving sensor IDs in place.
2) Please set `debug = yes` in `cfg/settings.cfg` and then post the output when you run the programme.

**Comment by wingers999** [comment]
ubidots section below:-

[Ubidots]
filename = ubidots
enabled = yes
showcost = no
token = bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0f
ID-BMP085-temp = 54ee074a7625422aff7bf44b
ID-BMP085-pres = 54ee05fb7625422ccda6d7ea
ID-DHT22-hum = 54edd9877625424f0f29f2d0
#ID-DHT22-temp = YYYYYYYYYYYYYYYYYYYYYYYY
ID-LDR = 54ee079a7625422d34362168
#ID-TGS2600 = YYYYYYYYYYYYYYYYYYYYYYYY
#ID-MiCS-2710 = YYYYYYYYYYYYYYYYYYYYYYYY
#ID-MiCS-5525 = YYYYYYYYYYYYYYYYYYYYYYYY
ID-Microphone = 54ee082d7625423163a80b0d
calibration = on
target = internet

Minor tweak has not helped, still getting nothing on screen from print output even with ubidots disabled

debug output below:-

INFO:__main__:  Success: Data successfully obtained from all sensors.
DEBUG:__main__: Dataset to output to <outputs.print.Print object at 0x4ee710>:
DEBUG:__main__: [{'description': 'BOSCH combined temperature and pressure sensor.', 'symbol': 'C', 'value': 17.5, 'breach': False, 'readingtype': 'sample', 'sensor': 'BMP085-temp', 'unit': 'Celsius', 'name': 'Temperature-BMP'}, {'description': 'BOSCH combined temperature and pressure sensor.', 'symbol': 'hPa', 'value': 994.1147636168866, 'breach': False, 'readingtype': 'sample', 'sensor': 'BMP085-pres', 'unit': 'Hectopascal', 'name': 'Pressure'}, {'description': 'A combined temperature and humidity sensor.', 'symbol': '%', 'value': 83.80000305175781, 'breach': False, 'readingtype': 'sample', 'sensor': 'DHT22-hum', 'unit': '% Relative Humidity', 'name': 'Relative_Humidity'}, {'description': 'A combined temperature and humidity sensor.', 'symbol': 'C', 'value': 16.5, 'breach': False, 'readingtype': 'sample', 'sensor': 'DHT22-temp', 'unit': 'Celsius', 'name': 'Temperature-DHT'}, {'description': 'A microphone to measure ambient noise', 'symbol': 'mV', 'value': 712.9032258064516, 'breach': False, 'readingtype': 'sample', 'sensor': 'Microphone', 'unit': 'millvolts', 'name': 'Volume'}]
DEBUG:__main__: ERROR:   Exception during output: 'Print' object has no attribute 'cal'

**Comment by haydnw** [comment]
OK, that's a different error, relating to Print. Please disable Print and confirm that Ubidots is working. That will mean I can then concentrate on the Print issue. Thanks.

**Comment by wingers999** [comment]
same error for ubidots = ERROR:   Exception during output: 'Ubidots' object has no attribute 'cal'

**Comment by wingers999** [comment]
problem seems to be if calibration = on in ubidots or print output - turning it to off solves problem and then works okay

**Comment by haydnw** [comment]
Ok thanks; I'm aware of that and am actually halfway through fixing at the moment. Will update this thread with commit ID when done.

**Comment by haydnw** [comment]
Same as issue #13; see discussion there.
