### ISSUE TITLE
Error csvoutput

### ISSUE THREAD

**Issue by geo81** [haydnw/AirPi#15]
Loading: OUTPUTS
Success: Loaded output plugin Print
ERROR:   Could not import output module csvoutput
ERROR:   Did not import output plugin CSVOutput: No module named calibration
Traceback (most recent call last):
  File "/home/pi/AirPi/airpi.py", line 1356, in <module>
    PLUGINSOUTPUTS = set_up_outputs()
  File "/home/pi/AirPi/airpi.py", line 604, in set_up_outputs
    raise excep
ImportError: No module named calibration

**Comment by haydnw** [comment]
Please confirm which version of the software you are using (airpictl.sh ver)

**Comment by geo81** [comment]
[AirPi] Current installed version and latest change:
commit 477c466a4b7fa0c09f5790e77387fe2da5add57a
Author: Haydn Williams <pi@hwmail.co.uk>
Date:   Mon May 11 19:23:54 2015 +0000

**Comment by haydnw** [comment]
Thanks. Please try latest commit on the 'development' branch (99e3bb).

**Comment by geo81** [comment]
It worked but know I get (not always): 

ERROR:   Failed to obtain data from these sensors: DHT22-hum, DHT22-temp


==========================================================
Loading: SETTINGS
Success: Loaded settings.
==========================================================
Loading: SUPPORTS
==========================================================
Loading: SENSORS
Success: Loaded sensor plugin BMP085-temp
Success: Loaded sensor plugin BMP085-pres
Success: Loaded sensor support plugin MCP3008
Success: Loaded sensor plugin DHT22-hum
Success: Loaded sensor plugin DHT22-temp
Success: Loaded sensor plugin LDR
Success: Loaded sensor plugin TGS2600
Success: Loaded sensor plugin MiCS-2710
Success: Loaded sensor plugin MiCS-5525
Success: Loaded sensor plugin UV
==========================================================
Loading: OUTPUTS
Success: Loaded output plugin Print
Success: Loaded output plugin CSVOutput
==========================================================
Loading: NOTIFICATIONS
INFO:    No Notifications enabled.
==========================================================
Loading: METADATA
Run started............15:26 on Friday 29 May 2015
Operator...............Dr. O. Perator
Raspberry Pi name......raspberrypi
Raspberry Pi ID........0000000013264ce6
Sample frequency.......300 seconds
Initialising runs......5 seconds
==========================================================
Success: Setup complete.
==========================================================
INFO:    Sampling will start in 56 seconds.
INFO:    Sampling will start in 50 seconds.
INFO:    Sampling will start in 40 seconds.
INFO:    Sampling will start in 30 seconds.
INFO:    Sampling will start in 20 seconds.
INFO:    Sampling will start in 10 seconds.
INFO:    Doing initialising runs for 5 seconds.
INFO:    Starting sampling...
==========================================================
ERROR:   Failed to obtain data from these sensors: DHT22-hum, DHT22-temp

**Comment by haydnw** [comment]
Unfortunately the DHT22 is notoriously flaky, and can only be read a maximum of once per two seconds under ideal conditions. This is a limitation of the sensor, and its price point. You can try increasing the duration of the initialising runs back to the default of 15 seconds, but we still see this error on all of our units occasionally I'm afraid.
