### ISSUE TITLE
[FIX] No more error message when LDR is in complete darkness.

### ISSUE THREAD

**Issue by wingers999** [haydnw/AirPi#16]
NOT FIXED - updated to latest version and still crashes the AirPi software when the LDR gets complete darkness - disabled LDR sensor again and then the software works fine and has been running for hours

**Comment by haydnw** [comment]
Unable to reproduce this; works fine for me on a v1.2 AirPi board. Please include lines of output from a failed run when `debug = yes` in `cfg\settings.cfg`

**Comment by haydnw** [comment]
Please try again with latest version - some GitHub issues mean you may not actually have had the latest changes.

**Comment by wingers999** [comment]
okay - just updated - will see what happens when it gets dark later and let you know

**Comment by wingers999** [comment]
not dark yet so can't say if working - but I do notice that I have calibration on and it should be converting light level to lux, but print output still shows it as ohms?

**Comment by haydnw** [comment]
Is calibration switched on in `cfg\support.cfg` **and** against `[Print]` in `cfg\outputs.cfg`, and is the calibration function named correctly in `cfg\supports.cfg` (should be `func_Light_Level`, assuming the sensor name is `Light Level`).

*N.B.* Re-opened as LDR issue not yet confirmed as fixed.

**Comment by wingers999** [comment]
thanks for prompt reply - it was the func_Light_Level which was wrong - I had just uncommented the line in support.cfg where it was set as Light_Level rather than func_Light_Level

Will monitor pi tonight as it gets dark and let you know if it works

**Comment by haydnw** [comment]
Thanks - the functions have been updated / clarified in 4c0341d.

**Comment by wingers999** [comment]
Hi Hayden, been running in complete darkness for a couple or so hours now and no problems at all - so think this issue can now be marked as fixed
