### ISSUE TITLE
GPS Problem

### ISSUE THREAD

**Issue by svennnn** [haydnw/AirPi#20]
Hey there!
My AirPi works fine but I have got problems with the Adafruit GPS.
I installed gpsd, gpsd-clients and python-gps.  With cgps –s I get  positive results. 
But when I start the AirPi I get the following error:
```
INFO:    Doing initialising runs for 15 seconds.
DEBUG:__main__: GPS output (nan, nan, nan, 'fixed', 'indoor')
Traceback (most recent call last):
  File "/home/pi/AirPi/airpi.py", line 1388, in <module>
    dummy_runs(SETTINGS['DUMMYDURATION'])
  File "/home/pi/AirPi/airpi.py", line 1011, in dummy_runs
    read_gps(i)
  File "/home/pi/AirPi/airpi.py", line 1067, in read_gps
    reading["name"] = sensorplugin.valname
AttributeError: 'serial_gps' object has no attribute 'valname'
```

[AirPi] Current installed version and latest change:
```
commit 6a047b605f3263d4b791363b6df95740050f60a3
Author: Haydn Williams <pi@hwmail.co.uk>
Date:   Tue Jul 14 22:22:19 2015 +0000
Change: Partial fix for issue #19, error with HTTP output.
```

gpsd, gpsd-clients and python-gps:
```
Version 3.6-4+deb7u1
```

Thanks for your great help.
Kind regards
Sven

**Comment by haydnw** [comment]
Please could someone with working GPS try commit 608f585 and let me know whether it works. I'm still struggling with my GPS on Jessie.

**Comment by gasikan** [comment]
By Gasikan
I have tested the changes to the two files and the airpi.py program now runs with the gps running in the background.
Loading: SETTINGS
Success: Loaded settings.
==========================================================
Loading: SUPPORTS
==========================================================
Loading: SENSORS
Success: Loaded sensor plugin BMP085-temp
Success: Loaded sensor plugin BMP085-pres
Success: Loaded sensor support plugin MCP3008
Success: Loaded sensor plugin DHT22-hum
Success: Loaded sensor plugin DHT22-temp
Success: Loaded sensor plugin LDR
Success: Loaded sensor plugin TGS2600
Success: Loaded sensor plugin Microphone
Success: Loaded sensor plugin UV
Success: Loaded sensor plugin GPS
==========================================================
Loading: OUTPUTS
Success: Loaded output plugin Print
==========================================================
Loading: NOTIFICATIONS
INFO:    No Notifications enabled.
==========================================================
Loading: METADATA
Run started............15:19 on Friday 16 October 2015

Time              : 2015-10-16 15:21:35
Temperature-BMP   :      20.70 C    (sample)
Pressure          :    1019.92 hPa  (sample)
Relative Humidity :      50.00 %    (sample)
Temperature-DHT   :      20.30 C    (sample)
Light Level       :     333.33 Ohms (sample)
Air Quality       :   54457.40 Ohms (sample)
Volume            :     264.52 mV   (sample)
UVI               :     645.16 mV   (sample)
[AirPi] Reached requested number of samples - stopping run.

[AirPi] Sampling stopping...
[AirPi] GPS controller stopping...
[AirPi] GPS controller stopped.
[AirPi] This run lasted 0h 2m 10s, and consisted of 20 samples.
I still have to sort out why the other outputs are not working but that will come later.
Many thanks for the help
I hope this is correct on Github as I have never used it before.
Regards
Dave

**Comment by haydnw** [comment]
Hi Dave,

That's great, thanks very much. Feel free to ask on the AirPi forum if you need general help with the outputs, and then if there are any problems with the actual AirPi code we can pick them up here again.

Regards,
Haydn

**Comment by haydnw** [comment]
Fixed in 608f585.

**Comment by gasikan** [comment]
Hi Haydn
Thanks for the reply I am now starting to work out how to add a wind speed
and rain guage to the sensors, so working from first principles to get the
units sorted out. the rain is simple as bucket tips volume over time so
simple count is ok but wind speed is not so easy depending on wether you
count revs or measure voltage generated.
I did make up a small add on board using vero strip to plug the UV sensor
into J3 which I could write up if there is a need.
Regards
Dave
 Gasikan

**Comment by svennnn** [comment]
Hi Haydn,
do you still struggling with your GPS on Jessie?

Try to edit this..
```
/etc/default/gpsd
```
.. and paste
```
DEVICES="/dev/ttyAMA0"
```

Regards
Sven

**Comment by haydnw** [comment]
Sven, that is fantastic, thank you so much! Took about 5 seconds to do it, and GPS now works perfectly! I've added a line to the installation instructions in the latest commit (fce8f75).
