### ISSUE TITLE
git not installed in install.sh

### ISSUE THREAD

**Issue by kawalex** [haydnw/AirPi#23]
Hi,
Just use your install procedure on a fresh RPI and I noticed that git is not install by the install.sh while it is required further in the install script.
Maybe an apt-get install git can be inserted in that script ?
Regards.
Alexandre

**Comment by haydnw** [comment]
Hi Alexandre,

What version of Raspbian are you using? Git has always been pre-installed on the Raspberry Pi Foundation releases of Wheezy and Jessie which I have used.

Thanks,
Haydn

**Comment by kawalex** [comment]
Hi,

I’ve installed from the last raspbian jessie lite from https://www.raspberrypi.org/downloads/raspbian/ <https://www.raspberrypi.org/downloads/raspbian/>.

Maybe the lilt version does not include GIT by default ?

Thanks.
Alexandre

**Comment by haydnw** [comment]
It seems Git isn't included in Jessie Lite. I'll have a look at adding a check for Jessie Lite and doing apt-get to install Git if required.

**Comment by haydnw** [comment]
Please could someone try the following as a Python script in Jessie Lite and let me know the output? I don't have anything available to test on at the moment.

```python
import platform
platform.linux_distribution()
```

**Comment by kawalex** [comment]
Hi,

Here it is:
>>> platform.linux_distribution()
('debian', '8.0', '')

Regards.
Alex.

Date: Sun, 13 Dec 2015 20:37:03 -0800
