### ISSUE TITLE
Rain Gauge convert the Bucket Tips to mm per hour

### ISSUE THREAD

**Issue by chrisf4lc0n** [haydnw/AirPi#25]
I was trying to implement it myself into the support.cfg but I have to admit I have failed...
Since 1 tip equals to 0.2794mm the equation should be something like:
Total of the tips times 0.2794mm in 3600 seconds and reset, but since I am an absolute Python I have no idea whatsoever on how to implement it...

**Comment by haydnw** [comment]
Not a software issue. Posted for discussion on forum: http://airpi.freeforums.net/thread/211/rain-gauge-hourly-rate
