### ISSUE TITLE
Raingauge error

### ISSUE THREAD

**Issue by chrisf4lc0n** [haydnw/AirPi#28]
TypeError: buckettip() takes exactly 1 argument (2 given)

**Comment by haydnw** [comment]
Thanks. Do you know where this method is called from? I'm just wondering if we can't amend the call rather than changing the method signature to include a value that we don't then use?

**Comment by chrisf4lc0n** [comment]
Mate it took me nearly half an hour just to find where does it call them 2 arguments... I am an absolute Python noob, it was more sheer luck that I found it and worked it out, than anything else. I will however try to pick something more from this code up and may come with the answer...

**Comment by chrisf4lc0n** [comment]
I do have another problem... I edited the ubidots.py and added ID-Raingauge.I also added the same entry to the output.cfg but no data seems to transmitted to UbiDots...? I will try to debug it once back from work.

**Comment by chrisf4lc0n** [comment]
When I print the amount of rain on the screen everything seems to be working and gives me reliable value of pulse counts depending on that how many times I tip the sensor, but no data gets sent to UbiDots.

**Comment by chrisf4lc0n** [comment]
{'description': 'A rain gauge.', 'symbol': '', 'value': 0, 'breach': False, 'readingtype': 'pulseCount', 'sensor': 'Maplin_N77NF', 'unit': '', 'name': 'Bucket_tips'}

It seems to be similar to the rest of the outputs, but Ubidots is not representing anything...

**Comment by haydnw** [comment]
I've added an argument called "channel" instead, since that seems to be common practice (see links in function docs).
