### ISSUE TITLE
Hangs on "INFO:    Doing initialising runs for 15 seconds."

### ISSUE THREAD

**Issue by edent** [haydnw/AirPi#37]
When I run `airpictl.sh normal` the process seems to freeze at  "INFO:    Doing initialising runs for 15 seconds."

Have left it for several minutes. No change. Won't respond to `ctrl`+`c`.

New Raspberry Pi 2. AirPi 1.4 (previously working on an old Pi).

Fresh install of Jessie Lite. Have updated and rebooted.

Full output is:

```
[AirPi] Starting normal AirPi sampling.
[AirPi] This run will end if you log out.
[AirPi] Press Ctrl + C to stop.
==========================================================
Loading: SETTINGS
Success: Loaded settings.
==========================================================
Loading: SUPPORTS
Success: Loaded support plugin Calibration
==========================================================
Loading: SENSORS
Success: Loaded sensor plugin BMP085-temp
Success: Loaded sensor plugin BMP085-pres
Success: Loaded sensor support plugin MCP3008
Success: Loaded sensor plugin DHT22-hum
Success: Loaded sensor plugin DHT22-temp
Success: Loaded sensor plugin LDR
Success: Loaded sensor plugin TGS2600
Success: Loaded sensor plugin MiCS-2710
Success: Loaded sensor plugin MiCS-5525
Success: Loaded sensor plugin Microphone
==========================================================
Loading: OUTPUTS
Success: Loaded output plugin Print
==========================================================
Loading: NOTIFICATIONS
INFO:    No Notifications enabled.
==========================================================
Loading: METADATA
Run started............10:36 on Monday 02 May 2016
Operator...............Dr. O. Perator
Raspberry Pi name......AirPi
Raspberry Pi ID........00000000xxxxxxxx
Sample frequency.......5 seconds
Initialising runs......15 seconds
==========================================================
Success: Setup complete.
==========================================================
INFO:    Sampling will start in 43 seconds.
INFO:    Sampling will start in 40 seconds.
INFO:    Sampling will start in 30 seconds.
INFO:    Sampling will start in 20 seconds.
INFO:    Sampling will start in 10 seconds.
INFO:    Doing initialising runs for 15 seconds.
```

Any way to tell what's causing the problem?

Thanks :-)

**Comment by edent** [comment]
Ah, appears to be the dht22 issue - http://airpi.freeforums.net/thread/207/gets-stuck-doing-initialising-seconds

I disabled it in `cfg/sensors.cfg` and it works.

I also had to disable TGS2600 as I was getting
`Error: Check wiring for the TGS2600 measurement, no voltage detected on ADC input 1`

**Comment by PCAssistSoftware** [comment]
I had this issue - dht22 didn't work with pi2 due to driver issue

see [http://forums.pimoroni.com/t/raspberry-pi-2-and-airpi-1-4/576](url) and [http://airpi.freeforums.net/thread/174/airpi-1-4-rasperry-pi2](url)

I fixed it by using new dhtreader.so as per post 7 here = [http://forums.pimoroni.com/t/raspberry-pi-2-and-airpi-1-4/576/7](url)

**Comment by edent** [comment]
Many thanks @wingers999!

For those who follow.
- Grab the file `wget http://solarius.net/airpi/dhtreader.zip`
- Unzip it `unzip dhtreader.zip`
- Put it in the right place `mv dhtreader.so ~/AirPi/sensors/`

Just need to work out the TGS2600 issue now!

**Comment by PCAssistSoftware** [comment]
your welcome
Sorry can't help with TGS2600 as my board didn't come with that sensor as it wasn't standard with the kit

**Comment by edent** [comment]
Ah, mine neither :-)
