### ISSUE TITLE
HTML output - not all graphs update correctly

### ISSUE THREAD

**Issue by wingers999** [haydnw/AirPi#8]
Using HTML output - all working fine and showing correct readings/headings, but not all of the graphs seem to update correctly

i.e. AirPi been running 3 hours, top graph for Temperature-BMP is showing full 3 hours in the graph, but most of the others just showing an hour or less and not updating to show full period that AirPi has been sampling

**Comment by tvoverbeek** [comment]
Had the same problem when using Chrome (on OSX Yosemite)
When using Firefox or Safari, all graphs update correctly.
If you are using Chrome, clear the browser cache and reload the page.
I believe it is a Chrome issue (to aggressive caching ??)

**Comment by wingers999** [comment]
Thanks for your reply - have tried it with IE and Firefox and it appears to work fine - so must be something to do with caching in Google Chrome
