### ISSUE TITLE
error in ubidots.py file stopping LDR readings being uploaded

### ISSUE THREAD

**Issue by wingers999** [haydnw/AirPi#9]
outputs\ubidots.py      line 31  remove extra space showing after   ID-LDR

**Comment by haydnw** [comment]
Thanks. Fixed in [c0a67c66fc0cfbf0f6197f09c3d106e8d1c3ab84](https://github.com/haydnw/AirPi/commit/c0a67c66fc0cfbf0f6197f09c3d106e8d1c3ab84).
